apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: default
  uid: 74be81c0-e6b8-45e5-af26-ac5eb878a595
  resourceVersion: '1376'
  creationTimestamp: '2023-10-04T19:18:34Z'
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: v1
      time: '2023-10-04T19:18:34Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:openmetadata-mysql-password: {}
        f:type: {}
  selfLink: /api/v1/namespaces/default/secrets/mysql-secrets
  labels:
    k8slens-edit-resource-version: v1
data:
  openmetadata-mysql-password: b3Blbm1ldGFkYXRhX3Bhc3N3b3Jk
type: Opaque